version: "3.9"
services:
  weather:
    container_name: auth-service
    build:
      context: ./
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "8095:8095"
    env_file: ./auth-service/.env
    networks:
      - spring
    restart: always

networks:
  spring:
    name: spring